### ISSUE TITLE
终端播放器是什么？例如安卓屏需要安装的软件是什么呢

### ISSUE THREAD

**Issue by JustHave1Try** [nulijiabei/winxplay#1]

**Comment by nulijiabei** [comment]
@JustHave1Try 
https://github.com/nulijiabei/xplay 为树莓派定制
https://github.com/nulijiabei/winxplay 为Win10定制
另外支持，Linux，Android，系统，和 Intel，AMD，NVIDIA 显卡
现在开放出来的只有，树莓派和WIN版本，没有精力同时维护所有平台版本 ....
如果需要 android 版本您可以留下邮箱，如果其它系统或平台需要定制 ...
